language: node_js 
sudo: required 
dist: trusty 
yarn: false
node_js: 
  - "10.9.0" 
 
before_script: 
  - sudo apt-get install nodejs-legacy
  - export CHROME_BIN=/usr/bin/google-chrome 
  - sudo apt-get update 
  - sudo apt-get install -y libappindicator1 fonts-liberation 
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb 
  - sudo dpkg -i google-chrome*.deb 
  - export DISPLAY=:99.0 
  - sh -e /etc/init.d/xvfb start 
  - npm install -g vue-cli
  - cd quasar
  - npm install -g quasar-cli
  - npm install strip-ansi@=3.0.1
  - npm install
  - quasar build
